### ISSUE TITLE
Add emmet to compatibility list | Tab key deactivated in .htm files

### ISSUE THREAD

**Issue by fuunnx** [dqsully/language-octobercms#2]
Hi, my tab key is deactivated in my .htm files because of this keybinding :

<img width="882" alt="capture d ecran 2015-11-05 a 21 56 44" src="https://cloud.githubusercontent.com/assets/5963805/10981450/29233128-8408-11e5-9bc2-9cbc7fa3b6b5.png">

Deactivating it or installing emmet solves the problem ;)

**Comment by dqsully** [comment]
Hmm, I'll see what I can do.

**Comment by dqsully** [comment]
That keymap should now be disabled when Emmet is not installed.
