### ISSUE TITLE
Code Section isn't colorized anymore

### ISSUE THREAD

**Issue by AlexisWalravens** [dqsully/language-octobercms#5]
Hi,

It's been a while that the php code section between the 2 `==` isn't colorized.
Could you take a look at it ?

Thanks :)

**Comment by dqsully** [comment]
Thanks for bringing this up, it should be fixed now if you update to the latest version. I don't use this package much anymore so I'm not aware of when it breaks. So please, if you find any issues like this in the future, feel free to create an issue about it and I'll fix it.

**Comment by AlexisWalravens** [comment]
I don't know how you do to fix everything I report to you so quickly.
Thank you :)
